### ISSUE TITLE
Мерч - описание 

### ISSUE THREAD

**Issue by fruktoviy** [torin-asakura/follow-the-compass#27]
T-Shirt (Gildan, Canada)
"Follow The Compass" T-Shirt (Black/White)

- Highest quality
- This Unisex T-Shirt/ is 100% Cotton construction
- Classic fit
- Without side seams
- Tearaway label
- Silk-Screen Printing

Футболка (Gildan, Канада)
"Follow The Compass" футболка (Черная/Белая)

- Высокое качество
- Футболка унисекс/ изготовлена из 100% хлопка
- Классическая посадка
- Без боковых швов
- Отрывная этикетка
- Нанесение: шелкография

**Comment by fruktoviy** [comment]
+ до конца лета 2 CD в подарок! 
Imagination и Inside

**Comment by fruktoviy** [comment]
таблица размеров пока вот в таком варианте. там где покупали футболки другой сетки размеров нет. но по ней все понятно, более информативно чем обычный обхват плеч талии и тп.
[https://disk.yandex.ru/d/XxO-ijqnqFKiuQ](url)

**Comment by TorinAsakura** [comment]
https://followthecompass.ru/product/futbolka-uniseks/
