### ISSUE TITLE
Reverbnation

### ISSUE THREAD

**Issue by TorinAsakura** [torin-asakura/follow-the-compass#28]
# ЗАДАЧА
Положить треки в формате wav в наше облако

# ИДЕЯ
У нас вполне подходящая музыка для многих сериалов, фильмов и даже игр
Я разверну на reverbnation нашу страничку, посмотрим, может сможем где-нибудь поучавствовать

**Comment by fruktoviy** [comment]
На ревер была страница. Сейчас она заброшена, поскольку толку от нее вообще нет. Для чего ещё нужны треки в вав? Если только для страницы в рев, то это не нужно делать.

**Comment by TorinAsakura** [comment]
> На ревер была страница. Сейчас она заброшена, поскольку толку от нее вообще нет. Для чего ещё нужны треки в вав? Если только для страницы в рев, то это не нужно делать.

Почему не нужно? Ты вообще знаешь для чего Реверб?

**Comment by fruktoviy** [comment]
log - followthecompass@yandex.ru
pa - b22apr15aMz

**Comment by fruktoviy** [comment]
логин и пасс в лс
